# This is a basic workflow that is manually triggered

name: Develop Build

on:
  push:
    branches: [ develop ]

jobs:
  build:
    name: Compile and Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        spark: [2.4, 3.0]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Source Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B -P spark_${{ matrix.spark }} clean install
  code_quality:
    name: Code Quality
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Source Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: mvn -B -DrepoToken=$coverallsToken clean install scoverage:report coveralls:report
