name: Debug

on: workflow_dispatch

jobs:
  print-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print secret value
        run: |
          echo "test"
